# Utilizar está versão CASO for necessário passar testes pelo TRAVIS.CI com packages sendo instalados por : docker-php-ext
FROM php:fpm-alpine3.14

# adicionar os packages do alpine necessários para configurar o cache/ configs do nginx/ adicionar envsub
RUN apk upgrade && apk update && apk add -U libmcrypt-dev \
    autoconf \
    build-base \
    icu-dev \
    gettext

# PHP_CPPFLAGS é utilizado pelos scripts do docker-php-ext-* 
ENV PHP_CPPFLAGS="$PHP_CPPFLAGS -std=c++11"

# Instalando as dependências do PHP e ativando elas
RUN docker-php-ext-install mysqli \
    opcache \
    intl \
    && docker-php-ext-enable mysqli \
    opcache \
    intl 

# Configuar o opcache
RUN { \
        echo 'opcache.memory_consumption=128'; \
        echo 'opcache.interned_strings_buffer=8'; \
        echo 'opcache.max_accelerated_files=4000'; \
        echo 'opcache.revalidate_freq=2'; \
        echo 'opcache.fast_shutdown=1'; \
        echo 'opcache.enable_cli=1'; \
    } > /usr/local/etc/php/conf.d/php-opocache-cfg.ini

# COPY ./php.ini /usr/local/etc/php/php.ini Caso necessite de modificar a .ini

# Copiar e modificar as permissões para utilizar no APP
COPY --chown=www-data:www-data ./src /var/www/src
WORKDIR /var/www/src

# Serve para expor pelo server as portas, porém nao tem outro app rodando junto
EXPOSE 80 443

# Criar permissões para poder execultar o script de inicialização
COPY ./config/iniciar-servicos.sh /etc/iniciar-servicos.sh
RUN chmod +x /etc/iniciar-servicos.sh

CMD /bin/bash -c "envsubst '\$herokusqlHost,\$herokusqlDatabase,\$herokusqlPassword,\$herokusqlUser' < /var/www/html/php/conexao.php > /var/www/html/php/conexao.php && /etc/iniciar-servicos.sh"

